# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: cruizen_arlon_test 
theme: windmill
#  name: gitbook
#  name: 'rtd-dropdown'
nav:
  - Home: index.md
  - Readme: about.md
  - Arlon_Help: help.md
  - Arlon_Design: design.md

#theme: ivory
edit_uri: edit/main/docs/
repo_url: https://github.com/cruizen/arlon
repo_name: cruizen/arlon
