# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: cruizen_arlon_test 
theme:
  name: null
  custom_dir: cinder
  colorscheme: github
  highlightjs: true

nav:
  - Home: index.md
  - Specimen: specimen.md
  - Arlon_About: readme.md
  - Arlon_Help: help.md
  - Arlon_Design: design.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true

#  name: gitbook
#  name: 'rtd-dropdown'
#theme: ivory
repo_url: https://github.com/cruizen/arlon
repo_name: cruizen/arlon
