# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: cruizen_arlon_test 
theme:
  name: null
  custom_dir: 'cinder'
#  name: gitbook
#  name: 'rtd-dropdown'
#theme: ivory
repo_url: https://github.com/cruizen/arlon
repo_name: cruizen/arlon
